default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: peepmail_development

test:
  <<: *default
  database: peepmail_test

production:
  <<: *default
  database: peepmail_production
  username: peepmail
  password: <%= ENV['PEEPMAIL_DATABASE_PASSWORD'] %>
